### ISSUE TITLE
empty columns

### ISSUE THREAD

**Issue by YuriFontella** [Claviz/xlstream#53]
Hello, the ignoreEmpty option is not working.
I'm using version 2.5.3.

Was this supposed to be working?

Empty columns are not being returned.

```js
readableStreamFile = await getXlsxStream({
  filePath: job.data.path,
  withHeader: true,
  ignoreEmpty: false
})
```

**Comment by jansivans** [comment]
Hi. 
Can you provide example xlsx file and what you expect to be returned by xlstream?

**Comment by YuriFontella** [comment]
That and the spreadsheet:

![image](https://user-images.githubusercontent.com/4920619/219135408-49c1c187-9325-442b-ac61-712a44504050.png)

Result:
`{ name: 'Yuri Fontella', age: 23 }`

What I expected:
`{ name: 'Yuri Fontella', address: '', age: 23 }`

Am I doing something wrong?

**Comment by jansivans** [comment]
Seems like it is working as expected - `ignoreEmpty` option means "If true, empty **rows** won't be emitted." (not columns).
There is no option to include "empty columns" for each row because it can be done by yourself:
A header array is emitted for each row `[ 'name', 'address', 'age' ]` so you know that each object with data can have `address` column. 
If it doesn't - it means that column in this case is empty.

**Comment by YuriFontella** [comment]
I thought that the complete obj could come with the keys and empty values inside the raw. I didn't understand his difference to formatted.

But ok, my need was to come in the obj. And it doesn't work for me.

**Comment by AlexTimo** [comment]
@YuriFontella,

 you could easily accomplish this by padding the `obj` with missing key/value pairs, e.g.

```
readableStreamFile = await getXlsxStream({
  filePath: job.data.path,
  withHeader: true,
  ignoreEmpty: false
})  

readableStreamFile.on("data", (x) => { 
	for (const headerItem of x.header) {
		headerItem in x.raw.obj ? null : x.raw.obj[`${headerItem}`] = '';
	}
	console.log(x);
});
```

**Comment by AlexTimo** [comment]
@YuriFontella,

do you have any further questions? Can we close this issue?
